version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

  # Backend service - placeholder for future implementation
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=development
  #   networks:
  #     - app-network
  #   depends_on:
  #     - frontend

networks:
  app-network:
    driver: bridge
