application:
  commit-number: intellij
  environment: intellij

jwt:
  secret: "mySecretKey123456789012345678901234567890" # minimum 32 znaki
  expiration: 86400000 # 24 godziny w milisekundach

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true